const mongoose=require('mongoose')
// We can also make Seperate Schemas for these ddetails
const FormSchema=new mongoose.Schema({
    Full_Name:{
        type:String,
        required:true
    },
    Headline:{
        type:String,
        required:true
    },
    Company_Name:{
        type:String,
        required:true
    },
    Position:{
        type:String,
        required:true
    },
    Date_of_Joining:{
        type:Date,
        required:true
    },
    Date_of_Resign:{
        type:Date,
        required:true
    },
    Work_Description:{
        type:String,
        required:true
    },
    Used_Skills:{
        type:String,
        required:true
    },
    Skills_Name:{
        type:String,
        required:true
    },
    Years_of_Experince:{
        type:String,
        required:true
    },
    Project_Title:{
        type:String,
        required:true
    },
    Project_URL:{
        type:String,
        required:true
    },
    Project_Discription:{
        type:String,
        required:true
    },
    Project_Duration:{
        type:String,
        required:true
    },
    Certificate_Name:{
        type:String,
        required:true
    },
    Issuing_organisation:{
        type:String,
        required:true
    },
    Certificate_Link:{
        type:String,
        required:true
    },
    Issue_date:{
        type:String,
        required:true
    },
    Course_Name:{
        type:String,
        required:true
    },
    Issuing_organisation:{
        type:String,
        required:true
    },
    Email:{
        type:String,
        required:true
    },
    Phone:{
        type:Number,
        required:true
    },
    Skype_Id:{
        type:String,
        required:true
    }
    })


module.exports=mongoose.model('Form',FormSchema)